# Name: Kylan, Harry, Nick
# Description: This is the settings class
# Date: 11/08/2023

import math

RES = WIDTH, HEIGHT = 1200, 675
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 0

PLAYER_POS = 1.5, 4.5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (21, 69, 21)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

STEPS_BETWEEN_COLORS = 3
COLORS = ['darkslategray', 'teal', 'limegreen', 'greenyellow', 'floralwhite']
PIXEL_SIZE = 4
FIRE_WIDTH = WIDTH // PIXEL_SIZE
FIRE_HEIGHT = HEIGHT // PIXEL_SIZE
